# Generated by Django 5.0.6 on 2024-05-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailingstatus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingmessage',
            name='content',
            field=models.TextField(verbose_name='содержание'),
        ),
        migrations.AlterField(
            model_name='mailingmessage',
            name='title',
            field=models.CharField(max_length=150, verbose_name='заголовок'),
        ),
    ]
