# Generated by Django 5.0.6 on 2024-05-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailingmessage_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingstatus',
            name='status',
            field=models.CharField(choices=[('success', 'успешно'), ('fail', 'неуспешно')], max_length=50, verbose_name='статус попытки'),
        ),
    ]
