# Generated by Django 5.0.6 on 2024-05-16 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_alter_mailingstatus_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingsettings',
            name='next_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next_datetime'),
        ),
    ]
